[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "helper_scripts"
description = "Database Helper Package"
version = "0.5.0"
readme = {file = "readme.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
authors = [{ name = "Winston David Ssentongo", email = "winstondavid96@gmail.com" },{ name = "Samuel Kizza", email = "SK8@gmail.com" }]
maintainers = [{ name = "Winston David Ssentongo", email = "winstondavid96@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
requires-python = ">=3.5"
dependencies = [
    "psycopg2>=2.9",
    "google-api-python-client>=2.130.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7",
    "pytest-cov>=4"
]

[project.urls]
homepage = "https://github.com/winston1o1/helper-scripts.git"


[tool.setuptools]
packages = ["database_handler", "send_mail", "google_drive", "excel_tooling", "helper_scripts"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=database_handler --cov=send_mail --cov=excel_tooling --cov-report=term-missing --cov-fail-under=80 --ignore=tests/google_drive_tests"
